name = "zenlist-api"
type = "javascript"
account_id = "YOUR_ACCOUNT_ID"
workers_dev = true
main = "./api/index.js"
compatibility_date = "2026-02-10"

[env.production]
# Add production-specific settings here
