

name = "zenlist-api"
account_id = "81845f9b6a8496a989cbe0ba6a78ddc7"
workers_dev = true

main = "api/index.ts"
compatibility_date = "2026-02-10"
migrations_dir = "api/migrations"

[[d1_databases]]
binding = "DB"
database_name = "zenlist-db"
database_id = "8a187875-86b2-4bca-8113-c0397faec078"
migrations_dir = "api/migrations"


[env.production]
routes = ["https://zenlist.site/api/*"]
[[env.production.d1_databases]]
binding = "DB"
database_name = "zenlist-db"
database_id = "8a187875-86b2-4bca-8113-c0397faec078"
migrations_dir = "api/migrations"
